build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/app/byeolbyeolsseudam/config/CustomP6spySqlFormat.java, src/main/java/com/app/byeolbyeolsseudam/config/P6spySqlFormatConfiguration.java, src/main/java/com/app/byeolbyeolsseudam/config/QueryDslConfig.java, src/main/java/com/app/byeolbyeolsseudam/entity/Basket.java, src/main/java/com/app/byeolbyeolsseudam/entity/Review.java, src/main/java/com/app/byeolbyeolsseudam/entity/Spot.java, src/main/java/com/app/byeolbyeolsseudam/repository/MemberRepository.java, src/main/resources/application.yml, src/main/resources/templates/app/community/communityMain.html, src/main/resources/templates/app/community/communityRead.html, src/main/resources/templates/app/community/communitySearch.html, src/main/resources/templates/app/community/communityWrite.html, src/main/resources/templates/app/market/market.html
Config 파일 추가, 실시간 반영 설정 세팅, entity 메소드 추가합니다
=> Config 파일 추가, 실시간 반영 설정 세팅

src/main/resources/templates/app/notice/Notice.html, src/main/resources/templates/app/notice/NoticeDetail.html, src/main/resources/templates/app/program/program.html, src/main/resources/templates/app/program/programDetail.html, src/main/resources/templates/app/recycling/recycling.html, src/main/resources/templates/app/recycling/recyclingIntro.html
=> 야멜 파일 제외 , 타이블 수정

src/main/resources/templates/app/fix/footer.html, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/fix/headerpicker.html, src/main/resources/templates/app/main/main.html
main page, header, footer 수정완료
=> main page, header, footer 수정

src/main/resources/static/css/program/program.css, src/main/resources/static/js/market/market.js, src/main/resources/static/js/program/program.js, src/main/resources/templates/app/community/communityMain.html, src/main/resources/templates/app/market/market.html, src/main/resources/templates/app/program/program.html, src/test/java/com/app/byeolbyeolsseudam/entity/BadgeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/BannerTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/BasketTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/BoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CommentTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseFinishedTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/FileBoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MemberTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MybadgeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MycourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MypointTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MyprogramTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/NoticeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/OrderDetailTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/OrderTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/PickupAcceptTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/PickupTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ProductTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ProgramTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ReviewTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/SpotTest.java
Market, Program js 추가 및 Entity 단위테스트 파일 생성했습니다.
=> Market, Program js 추가 및 Entity 단위테스트 파일 생성

src/main/resources/static/css/notice/Notice.css, src/main/resources/static/js/fix/header.js, src/main/resources/templates/app/fix/headerLoginPicker.html, src/main/resources/templates/app/fix/headerpicker.html, src/main/resources/templates/app/notice/Notice.html, src/main/resources/templates/app/notice/NoticeDetail.html, src/main/resources/templates/app/pickup/pickMain.html, src/main/resources/templates/app/recycling/recycling.html, src/main/resources/templates/app/recycling/recyclingIntro.html
header 경로 수정, 기사 header 퍼블리싱
notice 경로 수정, recycling 수정
=> header, notice, recycling update

src/main/resources/static/css/join/joinCollector.css, src/main/resources/static/css/join/joinNormal.css, src/main/resources/static/js/join/joinCollectorStepTwo.js, src/main/resources/static/js/join/joinNormal.js, src/main/resources/templates/app/join/joinCollectorStepTwo.html, src/main/resources/templates/app/join/joinNormal.html
일반 회원가입, 기사 회원가입 이메일 중복 확인, 비밀번호 확인 퍼블리싱 수정 및 js 추가
=> 일반 회원가입, 기사 회원가입 이메일 중복 확인, 비밀번호 확인 추가

src/main/resources/static/js/admin/admin.js, src/main/resources/templates/app/admin/adminProgramAdd.html, src/main/resources/templates/app/admin/adminProgramModify.html
관리자페이지_프로그램 추가 수정 _수강시간,인원 int 변경 및 진행 날짜 추가했습니다
=> 관리자페이지_프로그램 추가 수정 _수강시간 인원 int 변경 및 진행날짜 추가

build.gradle, src/main/java/com/app/byeolbyeolsseudam/domain/ProgramDTO.java, src/main/java/com/app/byeolbyeolsseudam/entity/Program.java, src/main/java/com/app/byeolbyeolsseudam/repository/MypointRepository.java, src/main/resources/application.yml, src/test/java/com/app/byeolbyeolsseudam/entity/BadgeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/BoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CommentTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseFinishedTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/FileBoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MybadgeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MycourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MypointTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MyprogramTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ReviewTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/SpotTest.java
Entity 단위테스트 및 MypointRepository 생성했습니다
=> Entity 단위테스트 및 MypointRepository 생성

src/test/java/com/app/byeolbyeolsseudam/entity/NoticeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ProductTest.java
=> notice, product 단위테스트

src/main/java/com/app/byeolbyeolsseudam/domain/CourseDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/CourseFinishedDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/ProgramDTO.java, src/main/java/com/app/byeolbyeolsseudam/entity/Course.java, src/main/java/com/app/byeolbyeolsseudam/entity/CourseFinished.java, src/main/java/com/app/byeolbyeolsseudam/entity/Program.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseFinishedTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/FileBoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MybadgeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MycourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MypointTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MyprogramTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/SpotTest.java
Program, Course Entity 및 DTO 수정, Entity 단위테스트 업데이트합니다.
=> Program, Course Entity 및 DTO 수정, Entity 단위테스트

src/main/java/com/app/byeolbyeolsseudam/domain/CourseDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/PickupDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/ProgramDTO.java, src/main/java/com/app/byeolbyeolsseudam/entity/Course.java, src/main/java/com/app/byeolbyeolsseudam/entity/Pickup.java, src/main/resources/application.yml, src/test/java/com/app/byeolbyeolsseudam/entity/CourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MyprogramTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/SpotTest.java
Course, Program, Pickup Entity 및 DTO 수정 업데이트합니다.
=> Course, Program, Pickup Entity 및 DTO 수정

src/main/java/com/app/byeolbyeolsseudam/domain/ProductDTO.java, src/test/java/com/app/byeolbyeolsseudam/entity/BasketTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/NoticeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/OrderDetailTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/OrderTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ProductTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ReviewTest.java
Market 부분 product, order, orderDetail, basket, review 단위테스트
Notice 단위테스트 완료했습니다.
=> Market & Notice 단위테스트

src/test/java/com/app/byeolbyeolsseudam/entity/BannerTest.java
=> 배너 CRUD 단위테스트 - BannerTest

src/main/java/com/app/byeolbyeolsseudam/domain/BasketDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/BoardDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/CommentDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/CourseDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/CourseFinishedDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/MybadgeDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/MycourseDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/MypointDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/MyprogramDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/OrderDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/OrderDetailDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/PickupAcceptDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/PickupDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/ReviewDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/SpotDTO.java, src/main/java/com/app/byeolbyeolsseudam/entity/Basket.java, src/main/java/com/app/byeolbyeolsseudam/entity/Board.java, src/main/java/com/app/byeolbyeolsseudam/entity/Comment.java, src/main/java/com/app/byeolbyeolsseudam/entity/Course.java, src/main/java/com/app/byeolbyeolsseudam/entity/CourseFinished.java, src/main/java/com/app/byeolbyeolsseudam/entity/Mybadge.java, src/main/java/com/app/byeolbyeolsseudam/entity/Mycourse.java, src/main/java/com/app/byeolbyeolsseudam/entity/Mypoint.java, src/main/java/com/app/byeolbyeolsseudam/entity/Myprogram.java, src/main/java/com/app/byeolbyeolsseudam/entity/Order.java, src/main/java/com/app/byeolbyeolsseudam/entity/OrderDetail.java, src/main/java/com/app/byeolbyeolsseudam/entity/Pickup.java, src/main/java/com/app/byeolbyeolsseudam/entity/Review.java, src/main/java/com/app/byeolbyeolsseudam/entity/Spot.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseFinishedTest.java
Entity 및 DTO 수정 업데이트, 컴파일 빌드 확인했습니다.
=> Entity 및 DTO 수정 업데이트

src/main/java/com/app/byeolbyeolsseudam/domain/FileBoardDTO.java, src/main/java/com/app/byeolbyeolsseudam/entity/CourseFinished.java, src/test/java/com/app/byeolbyeolsseudam/entity/BadgeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/BoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CommentTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseFinishedTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/FileBoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MybadgeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MycourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MypointTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MyprogramTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/SpotTest.java
CourseFinished Entity 변경
Entity CRUD 단위 테스트 업데이트합니다.
=> CourseFinished Entity 변경 및 Entity CRUD 단위 테스트

src/test/java/com/app/byeolbyeolsseudam/entity/BasketTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/OrderDetailTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/OrderTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ProductTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ReviewTest.java
=> market 부분 단위테스트

src/test/java/com/app/byeolbyeolsseudam/entity/BannerTest.java
=> banner 단위테스트 완료

src/test/java/com/app/byeolbyeolsseudam/entity/PickupTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ProgramTest.java
pickupTest, programTest CRUD 단위테스트 진행했습니다
=> pickupTest, programTest CRUD단위테스트 진행

src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminService.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommunityService.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinService.java, src/main/java/com/app/byeolbyeolsseudam/service/jubgging/JubggingService.java, src/main/java/com/app/byeolbyeolsseudam/service/login/LoginService.java, src/main/java/com/app/byeolbyeolsseudam/service/main/MainService.java, src/main/java/com/app/byeolbyeolsseudam/service/market/MarketService.java, src/main/java/com/app/byeolbyeolsseudam/service/mypage/MypageService.java, src/main/java/com/app/byeolbyeolsseudam/service/notice/NoticeService.java, src/main/java/com/app/byeolbyeolsseudam/service/pickup/PickupService.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramService.java, src/main/java/com/app/byeolbyeolsseudam/service/recycling/RecyclingService.java
=> Service 파일 생성

src/main/java/com/app/byeolbyeolsseudam/domain/Criteria.java, src/main/java/com/app/byeolbyeolsseudam/domain/PageDTO.java
=> Criteria, Page 생성

src/main/java/com/app/byeolbyeolsseudam/entity/Badge.java, src/main/java/com/app/byeolbyeolsseudam/entity/Banner.java, src/main/java/com/app/byeolbyeolsseudam/entity/Basket.java, src/main/java/com/app/byeolbyeolsseudam/entity/Board.java, src/main/java/com/app/byeolbyeolsseudam/entity/Comment.java, src/main/java/com/app/byeolbyeolsseudam/entity/Course.java, src/main/java/com/app/byeolbyeolsseudam/entity/CourseFinished.java, src/main/java/com/app/byeolbyeolsseudam/entity/FileBoard.java, src/main/java/com/app/byeolbyeolsseudam/entity/Member.java, src/main/java/com/app/byeolbyeolsseudam/entity/Mypoint.java, src/main/java/com/app/byeolbyeolsseudam/entity/Notice.java, src/main/java/com/app/byeolbyeolsseudam/entity/Order.java, src/main/java/com/app/byeolbyeolsseudam/entity/Pickup.java, src/main/java/com/app/byeolbyeolsseudam/entity/Product.java, src/main/java/com/app/byeolbyeolsseudam/entity/Program.java, src/main/java/com/app/byeolbyeolsseudam/entity/Review.java, src/main/java/com/app/byeolbyeolsseudam/entity/Spot.java
=> Entity update 메소드 변경

src/main/java/com/app/byeolbyeolsseudam/entity/Basket.java
=> basket Builder update

src/main/java/com/app/byeolbyeolsseudam/domain/BoardDTO.java, src/main/java/com/app/byeolbyeolsseudam/entity/Mypoint.java
Mypoint Entity Builder 메소드 수정 업데이트합니다.
=> Mypoint Entity Builder 메소드 수정

src/main/java/com/app/byeolbyeolsseudam/domain/BasketDTO.java
=> BasketDTO 수정

src/main/java/com/app/byeolbyeolsseudam/entity/review/Review.java, src/test/java/com/app/byeolbyeolsseudam/entity/BasketTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/NoticeTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/OrderDetailTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/OrderTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ProductTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ReviewTest.java
=> Market, Notice 단위테스트 수정

src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramCustomRepositoryImpl.java, src/main/resources/static/css/program/program.css, src/main/resources/static/css/program/programDetail.css, src/main/resources/templates/app/program/program.html, src/main/resources/templates/app/program/programDetail.html, src/test/java/com/app/byeolbyeolsseudam/entity/PickupTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/ProgramTest.java
program, detail_css, html / pickupTest, programTest 수정 / program 검색 단위 테스트 진행하였습니다
=> program, detail_css, html / pickupTest, programTest 수정 / program 검색 단위 테스트

src/main/java/com/app/byeolbyeolsseudam/config/CustomP6spySqlFormat.java, src/main/java/com/app/byeolbyeolsseudam/controller/main/MainController.java, src/main/java/com/app/byeolbyeolsseudam/service/main/BannerService.java, src/main/java/com/app/byeolbyeolsseudam/service/main/MainService.java, src/main/resources/templates/app/main/main.html, src/test/java/com/app/byeolbyeolsseudam/entity/BannerTest.java
CustomP6spySqlFormat.java 추가, Banner Service 및 Controller 작성
bannerTest, BannerServiceTest 완료
=> CustomP6spySqlFormat.java 추가, Banner Service 및 Controller 작성

src/main/java/com/app/byeolbyeolsseudam/controller/join/JoinController.java, src/main/java/com/app/byeolbyeolsseudam/entity/pickupAccept/PickupAccept.java, src/main/java/com/app/byeolbyeolsseudam/repository/member/MemberRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/pickupAccept/PickupAcceptCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/pickupAccept/PickupAcceptCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinService.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinServiceImpl.java, src/test/java/com/app/byeolbyeolsseudam/entity/MemberTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/PickupAcceptTest.java
조인컨트롤러, pickAccept custom, member 레포티토리 설정, 조인 서비스, 단위테스트, (요번에 픽업없슴)
=> 조인컨트롤러, pickAccept custom, member 레포티토리 설정, 조인 서비스, 단위테스트, (요번에 픽업없슴)

src/main/java/com/app/byeolbyeolsseudam/controller/join/JoinController.java, src/main/java/com/app/byeolbyeolsseudam/entity/member/Member.java, src/main/java/com/app/byeolbyeolsseudam/repository/pickupAccept/PickupAcceptCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/pickupAccept/PickupAcceptCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinService.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/join/MemberJoinService.java, src/main/java/com/app/byeolbyeolsseudam/service/pickup/PickupService.java, src/main/java/com/app/byeolbyeolsseudam/service/pickup/PickupService2.java, src/main/resources/static/js/join/joinNormal.js, src/main/resources/templates/app/join/joinNormal.html, src/test/java/com/app/byeolbyeolsseudam/entity/PickupAcceptTest.java
커밋이 두개일텐데 하나는 수정 부분이고 , 하나는 서비스 파일 추가 커밋입니다
=> 일반회원가입 타임리프 js 수정, PickupAcceptCustom 수정, pickupaccept service 수정

src/main/java/com/app/byeolbyeolsseudam/controller/notice/NoticeController.java, src/main/java/com/app/byeolbyeolsseudam/repository/notice/NoticeCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/notice/NoticeCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/notice/NoticeRepository.java, src/main/java/com/app/byeolbyeolsseudam/service/notice/NoticeService.java, src/main/java/com/app/byeolbyeolsseudam/service/notice/NoticeServiceImpl.java, src/main/resources/templates/app/notice/Notice.html, src/main/resources/templates/app/notice/NoticeDetail.html, src/main/resources/templates/app/notice/searchPage.html
=> 공지사항 전체, 상세보기 가능

src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/BannerUploadController.java, src/main/java/com/app/byeolbyeolsseudam/controller/main/MainController.java, src/main/java/com/app/byeolbyeolsseudam/repository/banner/BannerCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/banner/BannerRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/banner/BannerRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/BannerUploadService.java, src/main/java/com/app/byeolbyeolsseudam/service/main/BannerService.java, src/main/resources/templates/app/admin/adminBannerAdd.html, src/main/resources/templates/app/admin/adminBannerList.html, src/main/resources/templates/app/main/main.html, src/test/java/com/app/byeolbyeolsseudam/entity/BannerTest.java
admin, main 관련 controller, html 수정 및 추가
file upload 관련 controller 추가
=> controller, html 수정 및 추가

src/main/java/com/app/byeolbyeolsseudam/controller/community/CommentController.java, src/main/java/com/app/byeolbyeolsseudam/controller/community/CommunityController.java, src/main/java/com/app/byeolbyeolsseudam/domain/comment/CommentDTO.java, src/main/java/com/app/byeolbyeolsseudam/repository/board/BoardCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/board/BoardCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/board/BoardRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/comment/CommentCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/comment/CommentCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/comment/CommentRepository.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommentService.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommentServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommunityService.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommunityServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/type/BoardCategory.java, src/main/resources/static/css/community/communityMain.css, src/main/resources/static/css/community/communityRead.css, src/main/resources/static/js/community/communityMain.js, src/main/resources/static/js/community/communityRead.js, src/main/resources/static/js/community/communityWrite.js, src/main/resources/templates/app/community/communityMain.html, src/main/resources/templates/app/community/communityRead.html, src/main/resources/templates/app/community/communitySearch.html, src/main/resources/templates/app/community/communityWrite.html, src/main/resources/templates/app/jubgging/jubggingIntro.html, src/test/java/com/app/byeolbyeolsseudam/entity/BoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CommentTest.java
Community 카테고리별 목록조회 기능 업데이트합니다.
=> Community 카테고리별 목록조회 업데이트

src/main/java/com/app/byeolbyeolsseudam/controller/program/ProgramController.java, src/main/java/com/app/byeolbyeolsseudam/controller/program/ProgramRestController.java, src/main/java/com/app/byeolbyeolsseudam/entity/program/Program.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramSearchService.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramService.java, src/main/resources/static/js/program/program.js, src/main/resources/templates/app/fix/header.html, src/main/resources/templates/app/fix/headerLogin.html, src/main/resources/templates/app/program/program.html, src/main/resources/templates/app/program/programDetail.html, src/main/resources/templates/app/recycling/recycling.html, src/test/java/com/app/byeolbyeolsseudam/entity/ProgramTest.java, src/test/java/com/app/byeolbyeolsseudam/service/ProgramTest.java
프로그램 전체, 검색어, 상태에 따른 목록 가져오기 / headerLogin,header 링크수정했습니다
=> 프로그램 전체, 검색어, 상태에 따른 목록 가져오기 / headerLogin,header 링크수정

build.gradle, src/main/java/com/app/byeolbyeolsseudam/controller/join/JoinController.java, src/main/java/com/app/byeolbyeolsseudam/controller/login/LoginController.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinService.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/join/MemberJoinService.java, src/main/java/com/app/byeolbyeolsseudam/service/login/MemberLoginService.java, src/main/resources/static/js/login/findPassword.js, src/main/resources/static/js/login/login.js, src/main/resources/templates/app/login/findPassword.html, src/main/resources/templates/app/login/login.html, src/test/java/com/app/byeolbyeolsseudam/entity/MemberTest.java
EMAIL 디펜던시 추가,  회원가입 추가 ,  로그인 추가, 임시비밀번호발급 추가,  타임리프 추가, JS 수정
=> EMAIL 디펜던시 추가,  회원가입 추가 ,  로그인 추가, 임시비밀번호발급 추가,  타임리프 추가, JS 수정

src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminNoticeController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminUserController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/BannerController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/BannerUploadController.java, src/main/java/com/app/byeolbyeolsseudam/domain/member/MemberDTO.java, src/main/java/com/app/byeolbyeolsseudam/domain/pickup/PickupDTO.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/AdminRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/notice/AdminNoticeRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminMemberService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminNoticeService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminPickService.java, src/main/java/com/app/byeolbyeolsseudam/service/main/BannerService.java, src/main/resources/static/js/admin/admin.js, src/main/resources/templates/app/admin/adminBannerAdd.html, src/main/resources/templates/app/admin/adminBannerList.html, src/main/resources/templates/app/admin/adminNotice.html, src/main/resources/templates/app/admin/adminNoticeAdd.html, src/main/resources/templates/app/admin/adminSideBar.html, src/main/resources/templates/app/admin/adminUserManage.html
adminController 수정
admin, banner, notice 관련사항 수정
=> adminController 수정

src/main/java/com/app/byeolbyeolsseudam/controller/market/MarketController.java, src/main/java/com/app/byeolbyeolsseudam/controller/market/ReviewController.java, src/main/java/com/app/byeolbyeolsseudam/repository/notice/NoticeCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/product/ProductCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/product/ProductCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/product/ProductRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/review/ReviewCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/review/ReviewCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/review/ReviewRepository.java, src/main/java/com/app/byeolbyeolsseudam/service/market/MarketService.java, src/main/java/com/app/byeolbyeolsseudam/service/market/MarketServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/market/ReviewService.java, src/main/java/com/app/byeolbyeolsseudam/service/market/ReviewServiceImpl.java, src/main/resources/static/css/market/marketDetail.css, src/main/resources/static/js/market/market.js, src/main/resources/static/js/market/marketDetail.js, src/main/resources/static/js/market/review.js, src/main/resources/templates/app/market/market.html, src/main/resources/templates/app/market/marketDetail.html
=> market 리뷰 작성

src/main/java/com/app/byeolbyeolsseudam/controller/join/JoinController.java, src/main/java/com/app/byeolbyeolsseudam/controller/login/LoginController.java, src/main/java/com/app/byeolbyeolsseudam/controller/pickup/PickupController.java, src/main/java/com/app/byeolbyeolsseudam/repository/member/MemberRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/pickupAccept/PickupAcceptCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/pickupAccept/PickupAcceptCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinService.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/login/MemberLoginService.java, src/main/java/com/app/byeolbyeolsseudam/service/pickup/PickupService2.java, src/main/resources/static/js/join/joinCollectorStepTwo.js, src/main/resources/templates/app/join/joinCollectorStepOneMap.html, src/main/resources/templates/app/join/joinCollectorStepTwo.html, src/main/resources/templates/app/login/findPasswordDone.html, src/main/resources/templates/app/pickup/pickWantedList.html, src/test/java/com/app/byeolbyeolsseudam/entity/PickupAcceptTest.java
=> 기사회원가입, 로그인, 비밀번호 찾기, 픽업 목록,

src/main/resources/static/js/community/communityMain.js, src/main/resources/static/js/community/communityRead.js
=> Community 상세보기 JS 업데이트

src/main/java/com/app/byeolbyeolsseudam/repository/admin/community/AdminBoardRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/community/AdminCommentRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/pickup/AdminPickupRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/main/MainRepository.java, src/test/java/com/app/byeolbyeolsseudam/entity/BannerTest.java
admin board,commtent  repository 수정
MainRepository 수정
=> admin board,commtent  repository 수정

src/main/resources/templates/app/program/program.html, src/main/resources/templates/app/program/programDetail.html, src/test/java/com/app/byeolbyeolsseudam/entity/ProgramTest.java
프로그램 _ 상세보기 페이지 데이터 가져오기 완성 
_ 목록 페이지 수정중 
_ test data 추가
=> 프로그램 _ 상세보기 페이지 / 목록 페이지 수정중 / test data

src/main/java/com/app/byeolbyeolsseudam/controller/market/MarketController.java, src/main/java/com/app/byeolbyeolsseudam/controller/notice/NoticeController.java, src/main/java/com/app/byeolbyeolsseudam/repository/notice/NoticeCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/notice/NoticeCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/product/ProductCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/service/notice/NoticeService.java, src/main/java/com/app/byeolbyeolsseudam/service/notice/NoticeServiceImpl.java, src/main/resources/templates/app/market/market.html, src/main/resources/templates/app/market/marketDetail.html, src/main/resources/templates/app/market/marketPayment.html, src/main/resources/templates/app/notice/Notice.html, src/test/java/com/app/byeolbyeolsseudam/entity/NoticeTest.java
=> Notice 검색 및 페이징 처리

src/main/java/com/app/byeolbyeolsseudam/controller/community/BoardController.java, src/main/java/com/app/byeolbyeolsseudam/controller/community/CommentController.java, src/main/java/com/app/byeolbyeolsseudam/controller/community/CommunityController.java, src/main/java/com/app/byeolbyeolsseudam/repository/board/BoardCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/board/BoardCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/comment/CommentCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/comment/CommentCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommentService.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommentServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommunityService.java, src/main/java/com/app/byeolbyeolsseudam/service/community/CommunityServiceImpl.java, src/main/resources/static/css/community/communityMain.css, src/main/resources/static/css/community/communityWrite.css, src/main/resources/static/js/community/commentModule.js, src/main/resources/static/js/community/communityMain.js, src/main/resources/static/js/community/communityModule.js, src/main/resources/static/js/community/communityRead.js, src/main/resources/static/js/community/communityWrite.js, src/main/resources/templates/app/community/communityMain.html, src/main/resources/templates/app/community/communityRead.html, src/main/resources/templates/app/community/communityWrite.html, src/test/java/com/app/byeolbyeolsseudam/entity/BoardTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/CourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/SpotTest.java
Community RESTFUL 변경 완료, 무한스크롤 추가 , 게시글 CRUD, 첨부파일 upload 업데이트합니다.
=> Community RESTFUL 변경 완료, 무한스크롤, CRUD, 첨부파일 upload 업데이트

src/main/java/com/app/byeolbyeolsseudam/config/WebMvcConfig.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminCommunityController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminMemberController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminNoticeController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminProgramController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/BannerController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/BannerUploadController.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/member/AdminMemberRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/program/AdminProgramRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/banner/BannerCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/banner/BannerRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminCommunityService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminMemberService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminNoticeService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminProgramService.java, src/main/java/com/app/byeolbyeolsseudam/service/main/BannerService.java, src/main/resources/templates/app/admin/adminBannerAdd.html, src/main/resources/templates/app/admin/adminBannerList.html, src/main/resources/templates/app/admin/adminBannerModify.html, src/main/resources/templates/app/admin/adminCommunityManage.html, src/main/resources/templates/app/admin/adminNotice.html, src/main/resources/templates/app/admin/adminProgram.html, src/main/resources/templates/app/admin/adminUserManage.html, src/main/resources/templates/app/main/main.html, src/test/java/com/app/byeolbyeolsseudam/entity/BannerTest.java
WebMvcConfig 추가
admin 관련 controller, service, repository, html 수정 및 추가
=> WebMvcConfig 추가

build.gradle, src/main/java/com/app/byeolbyeolsseudam/controller/join/JoinController.java, src/main/java/com/app/byeolbyeolsseudam/controller/login/KakaoController.java, src/main/java/com/app/byeolbyeolsseudam/controller/login/LoginController.java, src/main/java/com/app/byeolbyeolsseudam/domain/member/MemberDTO.java, src/main/java/com/app/byeolbyeolsseudam/entity/member/Member.java, src/main/java/com/app/byeolbyeolsseudam/repository/member/MemberRepository.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinService.java, src/main/java/com/app/byeolbyeolsseudam/service/join/JoinServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/kakao/KakaoService.java, src/main/java/com/app/byeolbyeolsseudam/service/login/MemberLoginService.java, src/main/java/com/app/byeolbyeolsseudam/service/pickup/PickupService2.java, src/main/resources/static/css/notice/NoticeSearch.css, src/main/resources/static/js/join/joinNormal.js, src/main/resources/templates/app/fix/headerLogin.html, src/main/resources/templates/app/join/joinCollectorStepOneMap.html, src/main/resources/templates/app/join/joinCollectorStepTwo.html, src/main/resources/templates/app/join/joinNormal.html, src/main/resources/templates/app/join/pickIntro.html, src/main/resources/templates/app/login/login.html, src/main/resources/templates/app/main/logoutMain.html, src/main/resources/templates/app/notice/NoticeSearch.html, src/test/java/com/app/byeolbyeolsseudam/entity/MemberTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/PickupTest.java
카카오 JSON 그레이들 추가, 맴버 ADDRESS 추가, 이메일중복검사추가, 기사가입, 공지사항 검색 추가
=> 카카오 JSON 그레이들 추가, 맴버 ADDRESS 추가, 이메일중복검사추가, 기사가입, 공지사항 검색 추가

src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminCommunityController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminNoticeController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminProductController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminProgramController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/BannerController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/ProgramUploadController.java, src/main/java/com/app/byeolbyeolsseudam/domain/program/ProgramDTO.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/member/AdminMemberRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/notice/AdminNoticeCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/notice/AdminNoticeRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/banner/BannerRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminCommunityService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminMemberService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminNoticeService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminProgramService.java, src/main/resources/templates/app/admin/adminComment.html, src/main/resources/templates/app/admin/adminCommunityManage.html, src/main/resources/templates/app/admin/adminNotice.html, src/main/resources/templates/app/admin/adminNoticeModify.html, src/main/resources/templates/app/admin/adminProductAdd.html, src/main/resources/templates/app/admin/adminProgram.html, src/main/resources/templates/app/admin/adminProgramAdd.html, src/main/resources/templates/app/admin/adminSideBar.html
ProgramDTO 수정
admin 관련 controller, service, repository, html 수정
프로그램 파일 업로드 컨트롤러(REST) 추가
=> ProgramDTO 수정,admin 관련 수정, 파일 업로드 컨트롤러(REST) 추가

src/main/java/com/app/byeolbyeolsseudam/controller/program/ProgramController.java, src/main/java/com/app/byeolbyeolsseudam/controller/program/ProgramDynamicRestController.java, src/main/java/com/app/byeolbyeolsseudam/controller/program/ProgramRestController.java, src/main/java/com/app/byeolbyeolsseudam/domain/Search.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramDynamicCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramDynamicCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramDynamicRepository.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramDynamicService.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramDynamicServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramSearchService.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramService.java, src/main/resources/static/js/program/program.js, src/main/resources/templates/app/program/program.html, src/test/java/com/app/byeolbyeolsseudam/entity/ProgramTest.java
=> 프로그램 동적쿼리 test 진행

src/main/java/com/app/byeolbyeolsseudam/controller/program/ProgramController.java, src/main/java/com/app/byeolbyeolsseudam/controller/program/ProgramDynamicRestController.java, src/main/java/com/app/byeolbyeolsseudam/controller/program/ProgramRestController.java, src/main/java/com/app/byeolbyeolsseudam/domain/Search.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramDynamicCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramDynamicCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/program/ProgramDynamicRepository.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramDynamicService.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramDynamicServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramSearchService.java, src/main/java/com/app/byeolbyeolsseudam/service/program/ProgramService.java, src/main/resources/templates/app/program/program.html, src/test/java/com/app/byeolbyeolsseudam/entity/ProgramTest.java
=> 프로그램 무한스크롤 구현 중 _ 중간 체크

src/main/java/com/app/byeolbyeolsseudam/controller/market/MarketController.java, src/main/java/com/app/byeolbyeolsseudam/controller/market/ProductController.java, src/main/java/com/app/byeolbyeolsseudam/repository/product/ProductCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/product/ProductCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/market/MarketService.java, src/main/java/com/app/byeolbyeolsseudam/service/market/MarketServiceImpl.java, src/main/resources/static/js/market/market.js, src/main/resources/static/js/market/marketModule.js, src/main/resources/templates/app/market/market.html
=> market 목록 조회

src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminNoticeController.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/notice/AdminNoticeCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/notice/AdminNoticeRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminNoticeService.java, src/main/resources/templates/app/admin/adminNotice.html, src/main/resources/templates/app/admin/adminSideBar.html
=> admin 공지사항 검색 및 페이징 처리

src/main/java/com/app/byeolbyeolsseudam/controller/mypage/MypageController.java, src/main/java/com/app/byeolbyeolsseudam/controller/mypage/MypageRestController.java, src/main/java/com/app/byeolbyeolsseudam/domain/myprogram/MyprogramDTO.java, src/main/java/com/app/byeolbyeolsseudam/entity/myprogram/Myprogram.java, src/main/java/com/app/byeolbyeolsseudam/repository/mypoint/MypointCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/mypoint/MypointCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/myprogram/MyprogramCustomRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/mypage/MypageService.java, src/main/java/com/app/byeolbyeolsseudam/service/mypage/MypageServiceImpl.java, src/main/java/com/app/byeolbyeolsseudam/type/MyprogramStatus.java, src/main/resources/static/css/community/communityRead.css, src/main/resources/static/js/community/communityMain.js, src/main/resources/static/js/community/communityRead.js, src/main/resources/static/js/mypage/mypageModule.js, src/main/resources/static/js/mypage/mypagePoint.js, src/main/resources/static/js/mypage/mypageProgram.js, src/main/resources/templates/app/community/communityMain.html, src/main/resources/templates/app/community/communityRead.html, src/main/resources/templates/app/community/communityWrite.html, src/main/resources/templates/app/mypage/mypagePoint.html, src/main/resources/templates/app/mypage/mypageProgram.html, src/test/java/com/app/byeolbyeolsseudam/entity/CourseTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MypointTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/MyprogramTest.java, src/test/java/com/app/byeolbyeolsseudam/entity/SpotTest.java
Community 첨부파일 화면 출력, Mypage 포인트조회, 수강내역 서비스 업데이트합니다.
=> Community 첨부파일 화면 출력, Mypage 포인트조회, 수강내역 서비스 업데이트

build.gradle, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminCommunityController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminMemberController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/AdminProgramController.java, src/main/java/com/app/byeolbyeolsseudam/controller/admin/BannerController.java, src/main/java/com/app/byeolbyeolsseudam/controller/main/MainController.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/community/AdminBoardCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/community/AdminBoardRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/community/AdminCommentCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/community/AdminCommentRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/member/AdminMemberCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/member/AdminMemberRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/notice/AdminNoticeRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/program/AdminProgramCustomRepository.java, src/main/java/com/app/byeolbyeolsseudam/repository/admin/program/AdminProgramRepositoryImpl.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminCommunityService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminMemberService.java, src/main/java/com/app/byeolbyeolsseudam/service/admin/AdminProgramService.java, src/main/resources/templates/app/admin/adminBannerList.html, src/main/resources/templates/app/admin/adminComment.html, src/main/resources/templates/app/admin/adminCommunityManage.html, src/main/resources/templates/app/admin/adminProgram.html, src/main/resources/templates/app/admin/adminProgramAdd.html, src/main/resources/templates/app/admin/adminProgramModify.html, src/main/resources/templates/app/admin/adminSideBar.html, src/main/resources/templates/app/admin/adminUserManage.html, src/main/resources/templates/app/main/main.html, src/test/java/com/app/byeolbyeolsseudam/entity/BannerTest.java
build.gradle dependency 추가
메인 페이지 경로 수정
admin 관련 controller, service, repository, html 수정
=> build.gradle dependency 추가
